### PR TITLE
n26: add English localisation

### PR DESCRIPTION
**Pull request by 3v1n0**
@hadess including it here if you're fine!

### CODE REVIEW

**Comment by hadess** [comment]
Wrong person.

**Comment by 3v1n0** [comment]
@hadess sorry, ahaha I was too used to your handle that I added an extra `s` :-)

**Comment by 3v1n0** [comment]
@hades fine with merging it here?

**Comment by hades** [comment]
Certainly :) Thanks for taking care of it, I was going to send you a PR but then totally lost track of it.

**Pull request merged**
